version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: admin
      POSTGRES_PASS: root
    ports:
      - 5432:5432
  redis:
    image: redis
    ports:
      - 6379:6379
  app:
    build: .
    environment:
      APP_ENV: development
    command: ["./wait-for-it.sh", "db:5432", "--", "go", "run", "main.go"]
    volumes:
      - .:/go/src/app
    ports:
      - "80:8080"
    depends_on:
      - db
      - redis
    links:
      - db
      - redis